In [7]:
# ground_module_cookbook.py
# Шпаргалка по работе с ground-модулем.
# Каждый кусочек можно копировать в ноутбук как есть.
# ВАЖНО: секции выполняются в порядке 0 → 1 → 2 → ...

# ==============================================================
# 0) ИНИЦИАЛИЗАЦИЯ — выполнять один раз в начале ноутбука
# ==============================================================

# 0a. Импорты — библиотеки
import pandas as pd
import random
from datetime import datetime

# 0b. Импорты — модули проекта
from ground_engine    import GroundEngine, create_ground_unit, GROUND_LOG_COLUMNS
from artillery_engine import artillery_strike
from force_manager    import ForceManager
from wm_tac_ops       import next_turn, determine_enemy_size, get_enemy_action, ai_arty_decide
import gspread
from google.oauth2.service_account import Credentials

# 0c. Google Sheets — подключение
service_account_info  ={
  "type": "service_account",
  "project_id": "findash-304114",
  "private_key_id": "ba5c7d0ad5e5e3b8efbed1d43a2a92061e72867a",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDumGcLSydvTf+h\nEb8dM6I+2v5eJan6L2lW+p6DNApp2YlKAvSPMWRu0mSj1oFlUNaV7Zwcfx7TqS4Y\nmhWBZvdLi93pIqGIEGWB1/wTCfs+0Ag+ez30U93bHupy9Tiy6qRdRQtO0eI1dBf+\np6TjdfVa8XEfN1gK1cn8zquHO0i++tTrwxEmnBVRIGXaicc7BXwYZqJhY8KhEjmY\nmBuCgphjjgWlAG4u+wcOHhZl2b64nc5xnDHqKJfuJ7oLgr+edeuPMxEZuPjOw5Bb\nWY8vSo0t90d+METES5K2UZ+/mMkEqYrz2XTpSHjvFi3RWAGmuwZgjKzBbh4PuEof\nkONL3Lh/AgMBAAECggEACkD5eLZHoRRwjnsFRBuCdwIRWXlz5yEffVHy+v+DDQ6A\nxHIBEaBVSR/4nEPtNq31MudNxLm/2OfV58/DadbDfPcrV8gZug++VQizuBu/NPFa\n0ViZjoUGLVMUT1FzmNjVrH55oG8LsjFlkJei0fWxUDG9I1LNEVYjwp4dKAgntbFb\ns6/6bNTRZQ0FEUKXlATzF8TyhX82tTKqYL1zUoM3UU7x3wB2VCjFzLdtam6yDzZm\ncq+S/GlgvopZpuMgQ2GGUIv5A5VVSL3yRTiIlIbZ5dQ26quD8OoR235ZnxH7DTK+\nPInh40InaQyMrYv1AzjWWws+29FVBYXDDelDtIOUqQKBgQD5/WJCQj66ycAh7HZH\n68jLUiJwD/QECyDAlocKdIwyWhtcP0gN8qcvjpvakAlmF8FfYmoGLkiG2jB6UWmb\npbrU1rT7Jer61fvWdM/EMBSU88t7PuBhM2j9wD2tkzxvQzPjeDM59TmgE9q+jImy\n+ginf8uRjBvmaLlzstqZLCrgtwKBgQD0VOOXyGSawbEO9ZsULpqeQgN0T7vNovPU\nOkyvzWzNVaNF63v+MlHv0BwxwkMCJu6NaOfCY+c7qzP+TtG6/VcWttSQm3h5ToRI\nUImJ0jmcuiNeL7rnwOAmBUibpoL4EzDmT1QGOP8bdmPcg2s6hokNfn1mXvpt7brX\nuhQUm6WOeQKBgQDWirKtEpUrUMHnWzwXdS8Z7x9G9SoB3lr5bTXvrx4yiEo63MRF\n1B3PHqB67mpih7iY16kOLOJpeQ9pqjzsK0swJiOj9mK3arV60z0Lrge73Y6f8tI2\nGRzdyQIl2Npg0lfRu/Kapu4Rh3iPV6VFSHfs6CwYeRnon6+or7ITCmix+QKBgBO0\n/R5y9VpeIQ/Z04ZPM/1ryaeJ/tXZPN1zTlgns4zkSWUMV1XrbRxwprWEu67iwP76\n5SaStEXlyy3J4bS5VlroqEB5qb/vC1Bh3pYVNLxlbxDbvLGQpwOqDW8wgQPNWHZb\nE6Xk1v66D9fraaywyUEjYK3vHzfaouVfhtsaqsHRAoGBAO6o9fWer+MIDoWb4gnX\nO6H/MHte2jGoCAr7Z2Sr3+faEUSqBfiTR01DfZcnNS3tzQYyvCQmQx7VVPh2kKiV\npNQY+Si+D+cb1kkvlesRWRGqbCUPWLmwWpuKPGJ89kG6romKUPe9DEcAvNBVG+wC\nnW45s81W+vpuM2yVSR1NULIT\n-----END PRIVATE KEY-----\n",
  "client_email": "wm-project@findash-304114.iam.gserviceaccount.com",
  "client_id": "104513908382942273394",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/wm-project%40findash-304114.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

creds = Credentials.from_service_account_info(
    service_account_info,
    scopes=["https://www.googleapis.com/auth/spreadsheets.readonly"],
)
client      = gspread.authorize(creds)
SPREADSHEET_ID = "19zobRN2kc4jLC6yPVUGk-JfE2PBQ4PWlS8FQ_sw3qs8"
spreadsheet = client.open_by_key(SPREADSHEET_ID)

def _load_sheet(name: str) -> pd.DataFrame:
    """Вспомогательная функция: загрузить лист из Google Sheets в DataFrame."""
    return pd.DataFrame(spreadsheet.worksheet(name).get_all_records())

# 0d. Загрузка таблиц из Google Sheets
#     ВСЁ это должно быть ДО создания engine!
injury_table    = _load_sheet("injuries")
contact_chance  = _load_sheet("contact_chance")
who_is_contact  = _load_sheet("who_is_contact")
enemy_action    = _load_sheet("enemy_action")
ai_arty_table   = _load_sheet("ai_arty_decision")
artillery_table = _load_sheet("artillery")

# 0e. Инициализация движка (все таблицы уже загружены — всё ок)
engine = GroundEngine(
    injury_table=injury_table,
    contact_chance=contact_chance,
    who_is_contact=who_is_contact,
    enemy_action=enemy_action,
)

# 0f. Загрузка бригад из Excel
player_manager = ForceManager.from_excel('player_brigade.xlsx')
enemy_manager  = ForceManager.from_excel('enemy_brigade.xlsx')

In [43]:
# 0g. Время
START_TIME   = datetime(2026, 5, 26, 7, 15)
current_time = START_TIME

In [2]:
# ==============================================================
# 1) СОЗДАТЬ ЮНИТ — беря DataFrame из экселя бригады
# ==============================================================
#
# Вариант A — берём конкретное подразделение по uid
inf_df = player_manager.get_formation_df(
    level='company',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B5-C1'],  # список uid формирований
    alive_only=True,
)
pc1 = create_ground_unit('pc1', side='blue', inf_df=inf_df)

## Вариант B — берём пехоту + броню (создаст mech-юнит)
#inf_df   = player_manager.get_formation_df('company', ['B5-C2'], alive_only=True)
#armor_df = player_manager.armor_df.head(3)                      # первые 3 живые машины

#pc2 = create_ground_unit('pc2', side='blue', inf_df=inf_df, armor_df=armor_df)

In [8]:
inf_df = player_manager.get_formation_df(
    level='company',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C1'],  # список uid формирований
    alive_only=True,
)
pc1 = create_ground_unit('pc1', side='blue', inf_df=inf_df)

inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C2-P1','B1-C2-P2',],  # список uid формирований
    alive_only=True,
)
pc2 = create_ground_unit('pc2', side='blue', inf_df=inf_df)

inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C2-P3',],  # список uid формирований
    alive_only=True,
)
pp1 = create_ground_unit('pp1', side='blue', inf_df=inf_df)


inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C3-P1',],  # список uid формирований
    alive_only=True,
)
pp2 = create_ground_unit('pp2', side='blue', inf_df=inf_df)


inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C3-P2',],  # список uid формирований
    alive_only=True,
)
pp3 = create_ground_unit('pp3', side='blue', inf_df=inf_df)


inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C3-P3',],  # список uid формирований
    alive_only=True,
)
pp4 = create_ground_unit('pp4', side='blue', inf_df=inf_df)
inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C2-P3',],  # список uid формирований
    alive_only=True,
)
pp1 = create_ground_unit('pp1', side='blue', inf_df=inf_df)


inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C3-P1',],  # список uid формирований
    alive_only=True,
)
pp2 = create_ground_unit('pp2', side='blue', inf_df=inf_df)


inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C3-P2',],  # список uid формирований
    alive_only=True,
)
pp3 = create_ground_unit('pp3', side='blue', inf_df=inf_df)


inf_df = player_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C3-P3',],  # список uid формирований
    alive_only=True,
)
pp4 = create_ground_unit('pp4', side='blue', inf_df=inf_df)

In [29]:

inf_df = enemy_manager.get_formation_df(
    level='squad',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C1-P1-S1',],  # список uid формирований
    alive_only=True,
)
c1_p1_s1 = create_ground_unit('c1_p1_s1', side='red', inf_df=inf_df)


inf_df = enemy_manager.get_formation_df(
    level='squad',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C1-P1-S2',],  # список uid формирований
    alive_only=True,
)
c1_p1_s2 = create_ground_unit('c1_p1_s2', side='red', inf_df=inf_df)


inf_df = enemy_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C1-P2',],  # список uid формирований
    alive_only=True,
)
c1_p2 = create_ground_unit('c1_p2', side='red', inf_df=inf_df)

In [50]:
inf_df = enemy_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C1-P3',],  # список uid формирований
    alive_only=True,
)
c1_p3 = create_ground_unit('c1_p3', side='red', inf_df=inf_df)


inf_df = enemy_manager.get_formation_df(
    level='platoon',           # 'battalion' / 'company' / 'platoon' / 'squad'
    formation_uids=['B1-C2-P1',],  # список uid формирований
    alive_only=True,
)
c2_p1 = create_ground_unit('c2_p1', side='red', inf_df=inf_df)

In [72]:
START_TIME = next_turn(START_TIME,side_a=[pc1,pc2,pp1,pp2,pp3,pp4])

2026-05-26 07:45:00
  Сторона A (player): умерли от ранений — 2

In [73]:
# ==============================================================
# 3) БИТВА между двумя юнитами
# ==============================================================
#

# Вариант B — с параметрами местности
result = engine.run_battle(
    attacker=c2_p1,
    defender=pp4,
    current_time=current_time,
    attacker_cover=2,
    defender_cover=1,          # враг в укрытии
    attacker_elevation=0,      # мы выше
    defender_elevation=0,
    distance=31,                # средняя дистанция
    defender_returns_fire=True,
)

# Результат и лог
print(result.result)           # 'победа' / 'поражение' / 'ничья' / ...
print(f"Потери blue: {result.defender_inf_losses} inf")
print(f"Потери red: {result.attacker_inf_losses} inf")
engine.logs

разгром
Потери blue: 3 inf
Потери red: 0 inf

,current_time,initiator,log_blue_id,log_blue_type,log_blue_inf_force,log_blue_arm_force,log_blue_cas_inf,log_blue_cas_armor,log_red_id,log_red_type,log_red_inf_force,log_red_arm_force,log_red_cas_inf,log_red_cas_armor,log_attack_type,log_result
0,2026-05-26 06:00:00,red,pp3,,,,5,,,mortar,20,,,,art_air_fire,
1,2026-05-26 06:00:00,red,pp1,inf,36,0,4,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,поражение
2,2026-05-26 06:00:00,red,pp1,inf,32,0,4,0,c1_p1_s2,inf,12,0,0,0,inf_attacks_inf,side_attack
3,2026-05-26 06:00:00,red,pp4,inf,36,0,3,0,c1_p2,inf,36,0,18,0,inf_attacks_inf,засада
4,2026-05-26 06:00:00,blue,pp2,inf,36,0,0,0,c1_p1_s2,inf,12,0,0,0,inf_attacks_inf,side_attack
5,2026-05-26 06:00:00,blue,,mortar,20,,,,c1_p1_s2,,,,0,,art_air_fire,
6,2026-05-26 06:00:00,red,pp1,,,,13,,,mortar,20,,,,art_air_fire,
7,2026-05-26 07:15:00,blue,pc1,inf,108,0,0,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,side_attack
8,2026-05-26 07:15:00,blue,pc2,inf,72,0,0,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,side_attack
9,2026-05-26 07:15:00,red,pp2,inf,36,0,2,0,c1_p1_s2,inf,12,0,1,0,inf_attacks_inf,победа
10,2026-05-26 07:15:00,red,pp2,inf,34,0,2,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,side_attack
11,2026-05-26 07:15:00,red,pc2,inf,72,0,1,0,c1_p3,inf,36,0,11,0,inf_attacks_inf,засада
12,2026-05-26 07:15:00,red,pp4,inf,33,0,0,0,c2_p1,inf,36,0,0,0,inf_attacks_inf,ничья
13,2026-05-26 07:15:00,blue,,rocket,1,,,,c1_p3,,,,14,,art_air_fire,
14,2026-05-26 07:15:00,blue,,mortar,20,,,,c2_p1,,,,1,,art_air_fire,
15,2026-05-26 07:15:00,red,pc2,,,,31,,,mortar,20,,,,art_air_fire,
16,2026-05-26 07:15:00,red,pp4,inf,33,0,3,0,c2_p1,inf,35,0,0,0,inf_attacks_inf,разгром

In [47]:
pp2

Unit(unit_id=pp2, overall_type=inf, personal_type=inf, size=PT, alive_df=36, cas_df=0, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 1, 'target_distance': 2, 'enemy_unit_id': '', 'berserk_mode': 0})

In [46]:
# ==============================================================
# 3) БИТВА между двумя юнитами
# ==============================================================
#

# Вариант B — с параметрами местности
result = engine.run_battle(
    attacker=pc2,
    defender=c1_p1_s1,
    current_time=current_time,
    attacker_cover=1,
    defender_cover=2,          # враг в укрытии
    attacker_elevation=0,      # мы выше
    defender_elevation=0,
    distance=4,                # средняя дистанция
    defender_returns_fire=False,
)


# Результат и лог
print(result.result)           # 'победа' / 'поражение' / 'ничья' / ...
print(f"Потери blue: {result.defender_inf_losses} inf")
print(f"Потери red: {result.attacker_inf_losses} inf")
engine.logs

side_attack
Потери blue: 0 inf
Потери red: 0 inf

,current_time,initiator,log_blue_id,log_blue_type,log_blue_inf_force,log_blue_arm_force,log_blue_cas_inf,log_blue_cas_armor,log_red_id,log_red_type,log_red_inf_force,log_red_arm_force,log_red_cas_inf,log_red_cas_armor,log_attack_type,log_result
0,2026-05-26 06:00:00,red,pp3,,,,5,,,mortar,20,,,,art_air_fire,
1,2026-05-26 06:00:00,red,pp1,inf,36,0,4,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,поражение
2,2026-05-26 06:00:00,red,pp1,inf,32,0,4,0,c1_p1_s2,inf,12,0,0,0,inf_attacks_inf,side_attack
3,2026-05-26 06:00:00,red,pp4,inf,36,0,3,0,c1_p2,inf,36,0,18,0,inf_attacks_inf,засада
4,2026-05-26 06:00:00,blue,pp2,inf,36,0,0,0,c1_p1_s2,inf,12,0,0,0,inf_attacks_inf,side_attack
5,2026-05-26 06:00:00,blue,,mortar,20,,,,c1_p1_s2,,,,0,,art_air_fire,
6,2026-05-26 06:00:00,red,pp1,,,,13,,,mortar,20,,,,art_air_fire,
7,2026-05-26 07:15:00,blue,pc1,inf,108,0,0,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,side_attack
8,2026-05-26 07:15:00,blue,pc2,inf,72,0,0,0,c1_p1_s1,inf,12,0,0,0,inf_attacks_inf,side_attack

In [71]:
pp4

Unit(unit_id=pp4, overall_type=inf, personal_type=inf, size=PT, alive_df=33, cas_df=3, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 1, 'target_distance': 31, 'enemy_unit_id': 'c2_p1', 'berserk_mode': 0})

In [39]:

# ==============================================================
# 4) ИИ — есть ли артудар врага по мне
# ==============================================================
#
# Объявляем ассеты врага в начале фазы (один раз)
enemy_assets = [
    {'weapon': 'mortar1', 'salvos_left': 1, 'shells_per_salvo': 20},
    {'weapon': 'mortar2', 'salvos_left': 1, 'shells_per_salvo': 20},
]

# В игровом цикле — вызываем каждый ход
current_turn  = 2
active_contacts = 1   # сколько боёв идёт прямо сейчас

to_fire = ai_arty_decide(
    assets=enemy_assets,
    deep_level=deep_level,
    active_contacts=active_contacts,
    current_turn=current_turn,      # int 1-8, НЕ datetime
    ai_arty_table=ai_arty_table,
    total_turns=8,
)

  [ИИ арта] ход 2 | deep=3 contact=1 | fire_d20=19 | стреляют: mortar2

In [60]:
# ==============================================================
# 5) АРТУДАР по юниту
# ==============================================================
#
# artillery_strike пишет строку в engine.logs автоматически
# (если передать logs=engine — объект с атрибутом .logs)

arty_result = artillery_strike(
    target_unit=pc2,      # кого бьём
    cover_level=0,                   # укрытие цели: 0-3
    shells_cnt=20,                    # кол-во снарядов в залпе
    weapon='mortar',                 # mortar / cannon / mlrs / rocket / bomb_250 / bomb_1000
    artillery_table=artillery_table,
    logs=engine,                     # engine.logs обновится автоматически
    current_time=current_time,
)


print(f"Убито: {arty_result['killed']}, тяжело: {arty_result['heavy']}, легко: {arty_result['light']}")

  Залп [mortar] cover=0 shells=20: killed=1, heavy=9, light=21 | alive after=40
Убито: 1, тяжело: 9, легко: 21

In [58]:
c1_p3

Unit(unit_id=c1_p3, overall_type=inf, personal_type=inf, size=PT, alive_df=11, cas_df=25, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 2, 'target_distance': 3, 'enemy_unit_id': 'pc2', 'berserk_mode': 0})

In [41]:
pp1

Unit(unit_id=pp1, overall_type=inf, personal_type=inf, size=PT, alive_df=15, cas_df=21, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 1, 'enemy_unit_id': '', 'berserk_mode': 0})

In [74]:

# ==============================================================
# 6) СОХРАНИТЬ ЛОГ в отдельный Excel
# ==============================================================
#
# Вариант A — только ground log (один лист)
engine.logs.to_excel('ground_battle_log.xlsx', index=False)

# Вариант B — несколько листов в одном файле
LOG_FILE = 'ground_battle_log.xlsx'

with pd.ExcelWriter(LOG_FILE, engine='openpyxl') as writer:
    engine.logs.to_excel(writer, sheet_name='ground_log', index=False)
    # дополнительные листы если нужны:
print(f"Лог сохранён: {LOG_FILE} ({len(engine.logs)} строк)")

Лог сохранён: ground_battle_log.xlsx (17 строк)

In [84]:

# ==============================================================
# 7) ОБНОВИТЬ ЭКСЕЛЯ БРИГАД
#    (записать статусы и kill-count из cas_df / alive_df обратно)
# ==============================================================
#
# После боя — применяем результаты юнитов к мастер-таблицам

# Если использовался generate_ground_units_with_armor:
player_manager.apply_many_battle_results([pc1,pc2,pp1,pp2,pp3,pp4])
#enemy_manager.apply_many_battle_results(enemy_units)


# Сохраняем обновлённые файлы
player_manager.save_to_excel('player_brigade.xlsx')
enemy_manager.save_to_excel('enemy_brigade.xlsx')

print("Экселя бригад обновлены")

Экселя бригад обновлены

In [82]:
pd.read_excel('ground_battle_log.xlsx')[['log_blue_cas_inf','log_red_cas_inf']].sum()

log_blue_cas_inf    68.0
log_red_cas_inf     45.0
dtype: float64