In [1]:
from datetime import datetime, timedelta
import itertools
from collections import Counter
import matplotlib.pyplot as plt
import random 
from typing import Optional
##### import random
from collections import Counter
import pandas as pd

import wm_unit as wmu
import wm_tac_ops as to




wf = pd.read_excel('A1.xlsx').iloc[:100]
ws = pd.read_excel('A1.xlsx').iloc[:10]
c1 = wmu.Unit(unit_id="c1",  alive_df=wf,  cas_df=pd.DataFrame(),side='blue')
c2 = wmu.Unit(unit_id="c2",  alive_df=ws,  cas_df=pd.DataFrame(),side='blue')


armor = pd.DataFrame([[1,'apc',9,8,0,0],
                  [2,'apc',9,8,0,0]],columns=['armor_id','type','transport','power','inf_kills','apc_kills'])

armor = wmu.Unit(unit_id="armor",  alive_df=armor,  cas_df=pd.DataFrame(),side='blue')

defenders = [armor]
attackers = [c1]

current_time = datetime(2026,1,21,13,0)
logs = pd.DataFrame()
cas_avacuated = pd.DataFrame()
cas_abandoned = pd.DataFrame()

In [2]:
mech =  wmu.Unit(unit_id="mech",  alive_df=ws, armor_part = armor , cas_df=pd.DataFrame(),side='blue')

In [3]:
mech

Unit(unit_id=mech, size=SQ, alive_df=10, cas_df=0, armor_part=2, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 0, 'enemy_unit_id': 'id1', 'berserk_mode': 0})

In [5]:

logs = c1.base_attack(mech,logs,current_time)

        ######
        c1
        ######

elev_pos 0 ?

cover_level 3 ?

target_distance 0 ?

enemy_unit_id mech ?

berserk_mode 1 ?

        ######
        mech
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id c1 ?

berserk_mode 0 ?

mech  вжат землю
c1 атаковал отряд mech c результатом разгром
Потери c1 0  Потери mech 7

Броня двигается?
Броня далеко?

c1 атаковал броню из отряда armor и подбил 2 единиц брони

In [6]:
mech

Unit(unit_id=mech, size=SQ, alive_df=0, cas_df=10, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 0, 'enemy_unit_id': 'c1', 'berserk_mode': 0})

In [7]:
logs

,time,attack_unit_side,attack_unit,attack_unit_size,attack_unit_alive_force,attack_cas,defend_unit,defend_unit_size,defend_unit_alive_force,defend_cas,result
0,2026-01-21 13:00:00,blue,mech,CM,100,0,c1,CM,100,0,side_attack
0,2026-01-21 13:00:00,blue,mech,CM,100,0,c1,CM,100,26,side_attack
0,2026-01-21 13:00:00,blue,mech,CM,100,0,c1,CM,74,25,side_attack

In [6]:
logs

,time,attack_unit_side,attack_unit,attack_unit_size,attack_unit_alive_force,attack_cas,defend_unit,defend_unit_size,defend_unit_alive_force,defend_cas,result
0,2026-01-21 13:00:00,blue,mech,CM,100,1,c1,CM,100,11,победа
0,2026-01-21 13:00:00,blue,mech,CM,99,2,c1,CM,89,12,победа

In [2]:
logs = c1.base_attack(c2,logs,current_time)

        ######
        c1
        ######

elev_pos 0 ?

cover_level 0 ?
2
target_distance 0 ?
2
enemy_unit_id id1 ?
c2
berserk_mode 0 ?


        ######
        c2
        ######

elev_pos 0 ?

cover_level 0 ?
2
target_distance 0 ?
2
enemy_unit_id id1 ?
c1
berserk_mode 0 ?

c2  вжат землю
c1 атаковал пехотный отряд c2 c результатом разгром
Потери c1 0  Потери c2 30

In [3]:

logs = mech.base_attack(c1,logs,current_time)

        ######
        mech
        ######

elev_pos 0 ?

cover_level 0 ?
2
target_distance 0 ?
2
enemy_unit_id id1 ?
c1
berserk_mode 0 ?


        ######
        c1
        ######

elev_pos 0 ?

cover_level 0 ?
2
target_distance 0 ?
2
enemy_unit_id id1 ?
mech
berserk_mode 0 ?

атака без ответа
0
aтака брони 0
победа
0.18 0.03
Потери mech 0 0
Потери c1 0
aтака пехоты победа 0 0

In [4]:
c1

Unit(unit_id=c1, size=CM, alive_df=100, cas_df=0, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 2, 'target_distance': 2, 'enemy_unit_id': 'mech', 'berserk_mode': 0})

In [5]:

logs = c1.base_attack(c2,logs,current_time)

        ######
        c1
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 2 ?

enemy_unit_id mech ?
c2
berserk_mode 0 ?


        ######
        c2
        ######

elev_pos 0 ?

cover_level 0 ?
2
target_distance 0 ?
2
enemy_unit_id id1 ?
c1
berserk_mode 0 ?

разгром
0.65 0.03
Потери c1 0 0
Потери c2 24

In [6]:
c2

Unit(unit_id=c2, size=CM, alive_df=76, cas_df=24, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 2, 'target_distance': 2, 'enemy_unit_id': 'c1', 'berserk_mode': 0})