In [1]:
from datetime import datetime, timedelta
import itertools
from collections import Counter
import matplotlib.pyplot as plt
import random 
from typing import Optional
from collections import Counter
import pandas as pd

import wm_unit as wmu
import wm_tac_ops as to

current_time = datetime(2026,1,21,13,0)
logs = pd.DataFrame()

wf = pd.read_excel('A1.xlsx').iloc[:100]
ws = pd.read_excel('A1.xlsx').iloc[:100]

c1 = wmu.Unit(unit_id="c1", overall_type="inf",personal_type="inf", alive_df=wf,  cas_df=pd.DataFrame(),side='blue')

armor = pd.DataFrame([[1,'apc',9,8,0,0],
                      [1,'apc',9,8,0,0],
                     [1,'apc',9,8,0,0],
                     [1,'apc',9,8,0,0],
                  [2,'apc',9,8,0,0]],columns=['armor_id','type','transport','power','inf_kills','apc_kills'])

armor = wmu.Unit(unit_id="armor", overall_type="arm",personal_type="arm", alive_df=armor,  cas_df=pd.DataFrame(),side='blue')

c1.armor_part = armor
c1.update_current_type()

In [2]:
c2 = wmu.Unit(unit_id="c2", overall_type="inf",personal_type="inf", alive_df=wf,  cas_df=pd.DataFrame(),side='blue')

In [3]:
logs = c1.base_attack(c2,logs,current_time)

        ######
        c1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

        ######
        c2
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

Механизированный c1 атакует пехотный отряд c2
атака без ответа
Бронированный armor наносит потери 16
атака без ответа
В стрелковом бою c1 атакует с результатом side_attack
Потери c1 0  Потери c2 36

In [5]:
logs

,current_time,log_attackers_id,log_attackers_type,log_attackers_inf_force,log_attackers_arm_force,log_attackers_cas_inf,log_attackers_cas_armor,log_defenders_id,log_defenders_type,log_defenders_inf_force,log_defenders_arm_force,log_defenders_cas_inf,log_defenders_cas_armor,log_attack_type,log_result
0,2026-01-21 13:00:00,c1,mech,100,5,0,0,c2,inf,100,0,52,0,mech_attacks_inf,side_attack

In [3]:
armor2 = pd.DataFrame([[1,'apc',9,8,0,0],
                      [1,'apc',9,8,0,0],
                     [1,'apc',9,8,0,0],
                     [1,'apc',9,8,0,0],
                  [2,'apc',9,8,0,0]],columns=['armor_id','type','transport','power','inf_kills','apc_kills'])

armor2 = wmu.Unit(unit_id="armor", overall_type="arm",personal_type="arm", alive_df=armor2,  cas_df=pd.DataFrame(),side='blue')

In [4]:
logs = armor2.base_attack(c1,logs,current_time)

        ######
        armor
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

        ######
        c1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

armor атаковал броню armor и подбил 2 единиц брони
атака без ответа
armor  вжат землю
Бронированный armor обстрелял пехотный отряд armor
Потери armor 3

In [5]:
logs

,current_time,log_attackers_id,log_attackers_type,log_attackers_inf_force,log_attackers_arm_force,log_attackers_cas_inf,log_attackers_cas_armor,log_defenders_id,log_defenders_type,log_defenders_inf_force,log_defenders_arm_force,log_defenders_cas_inf,log_defenders_cas_armor,log_attack_type,log_result
0,2026-01-21 13:00:00,armor,arm,0,5,0,0,c1,mech,100,5,3,2,armor_attacks_mech,side_attack

In [6]:




c1 = wmu.Unit(unit_id="c1",  alive_df=wf,  cas_df=pd.DataFrame(),side='blue')
c2 = wmu.Unit(unit_id="c2",  alive_df=ws,  cas_df=pd.DataFrame(),side='blue')


armor = pd.DataFrame([[1,'apc',9,8,0,0],
                  [2,'apc',9,8,0,0]],columns=['armor_id','type','transport','power','inf_kills','apc_kills'])

armor = wmu.Unit(unit_id="armor",  alive_df=armor,  cas_df=pd.DataFrame(),side='blue')

defenders = [armor]
attackers = [c1]


cas_avacuated = pd.DataFrame()
cas_abandoned = pd.DataFrame()

TypeError: Unit.__init__() missing 2 required positional arguments: 'overall_type' and 'personal_type'

In [2]:





mech =  wmu.Unit(unit_id="mech",  alive_df=ws, armor_part = armor , cas_df=pd.DataFrame(),side='blue')

In [3]:

armor = pd.DataFrame([[1,'apc',9,8,0,0],
                  [2,'apc',9,8,0,0],
                     [3,'apc',9,8,0,0],
                     [4,'apc',9,8,0,0],
                     [5,'apc',9,8,0,0]],columns=['armor_id','type','transport','power','inf_kills','apc_kills'])

armor1 = wmu.Unit(unit_id="armor1",  alive_df=armor,  cas_df=pd.DataFrame(),side='blue')

In [4]:
mech

Unit(unit_id=mech, size=CM, alive_df=100, cas_df=0, armor_part=2, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 0, 'enemy_unit_id': 'id1', 'berserk_mode': 0})

In [5]:
c1.armor_part = armor1

In [6]:
c1

Unit(unit_id=c1, size=CM, alive_df=100, cas_df=0, armor_part=5, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 0, 'enemy_unit_id': 'id1', 'berserk_mode': 0})

In [7]:
logs = mech.base_attack(c1,logs,current_time)

        ######
        mech
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

 2

enemy_unit_id id1 ?

 c1

berserk_mode 0 ?

        ######
        c1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

 2

enemy_unit_id id1 ?

 mech

berserk_mode 0 ?

mech атаковал броню c1 и подбил 0 единиц брони
c1 атаковал броню mech и подбил 1 единиц брони
Механизированный mech атакует пехотный отряд c1
атака без ответа
Бронированный armor наносит потери 0
В стрелковом бою mech атакует с результатом поражение
Потери mech 14  Потери c1 4

In [11]:
c1

Unit(unit_id=c1, size=CM, alive_df=96, cas_df=4, armor_part=5, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 2, 'enemy_unit_id': 'mech', 'berserk_mode': 0})

In [5]:
logs = armor1.base_attack(mech,logs,current_time)

        ######
        armor1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

        ######
        mech
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

armor1 атаковал броню armor и подбил 0 единиц брони
атака без ответа
armor  вжат землю
Бронированный armor1 обстрелял пехотный отряд armor
Потери armor 2

In [7]:
mech

Unit(unit_id=mech, size=SQ, alive_df=10, cas_df=0, armor_part=0, last_parameters={'elev_pos': 0, 'cover_level': 0, 'target_distance': 0, 'enemy_unit_id': 'id1', 'berserk_mode': 0})

In [ ]:

armor = pd.DataFrame([[1,'apc',9,8,0,0],
                  [2,'apc',9,8,0,0],
                     [3,'apc',9,8,0,0],
                     [4,'apc',9,8,0,0]],columns=['armor_id','type','transport','power','inf_kills','apc_kills'])

armor2 = wmu.Unit(unit_id="armor2",  alive_df=armor,  cas_df=pd.DataFrame(),side='blue')

In [5]:
logs = armor1.base_attack(armor2,logs,current_time)

        ######
        armor1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

 2

enemy_unit_id id1 ?

berserk_mode 0 ?

        ######
        armor2
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

 2

enemy_unit_id id1 ?

berserk_mode 0 ?

armor1 атаковал броню armor2 и подбил 2 единиц брони

In [6]:
distance = 0
cas=0
for i in range(len(armor1.alive_df)):
    chance = 5+ distance
    shoot = random.randint(1,10)
    if shoot > chance:
        cas+=1

In [9]:
armor1.last_parameters

{'elev_pos': 0,
 'cover_level': 0,
 'target_distance': 2,
 'enemy_unit_id': 'id1',
 'berserk_mode': 0}