In [ ]:
armor = pd.DataFrame([[1,'apc',9,8,0],
                  [2,'apc',9,8,0]],columns=['armor_id','type','transport','power','kill_count'])

In [2]:
from datetime import datetime, timedelta
import itertools
from collections import Counter
import matplotlib.pyplot as plt
import random 
from typing import Optional
##### import random
from collections import Counter
import wm_unit as wmu
import pandas as pd

def calculate_force(force):
    available_force = 0
    casualties = 0
    for i in force:
        available_force += len(i.alive_df)
        casualties += len(i.cas_df)
    return available_force,casualties

def next_turn(current_time):
    current_time += timedelta(minutes=15)
    print(current_time)
    return current_time


a1 = pd.read_excel('A1.xlsx').iloc[:25]
a2 = pd.read_excel('A1.xlsx').iloc[:25]
a3 = pd.read_excel('A1.xlsx').iloc[:25]
a4 = pd.read_excel('A1.xlsx').iloc[:25]
a5 = pd.read_excel('A1.xlsx').iloc[:25]
a6 = pd.read_excel('A1.xlsx').iloc[:75]

a1 = wmu.Unit(unit_id="a1",  alive_df=a1,  cas_df=pd.DataFrame())
a2 = wmu.Unit(unit_id="a2",  alive_df=a2,  cas_df=pd.DataFrame())
a3 = wmu.Unit(unit_id="a3",  alive_df=a3,  cas_df=pd.DataFrame())
a4 = wmu.Unit(unit_id="a4",  alive_df=a4,  cas_df=pd.DataFrame())
a5 = wmu.Unit(unit_id="a5",  alive_df=a5,  cas_df=pd.DataFrame())
a6 = wmu.Unit(unit_id="a6",  alive_df=a6,  cas_df=pd.DataFrame())

b1 = pd.read_excel('A1.xlsx').iloc[:100]
b2 = pd.read_excel('A1.xlsx').iloc[:100]
b1 = wmu.Unit(unit_id="b1",  alive_df=b1,  cas_df=pd.DataFrame())
b2 = wmu.Unit(unit_id="b2",  alive_df=b2,  cas_df=pd.DataFrame())

attackers = [b1,b2]
defenders = [a1,a2,a3,a4,a5,a6]

current_time = datetime(2026,1,9,6,0)

logs = pd.DataFrame()
logs = b1.attack_unit(a2,logs,current_time)

        ######
        b1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?


        ######
        a2
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

a2  вжат землю
атака без ответа
победа
0.18 0.03
25

In [3]:
logs

,time,our_unit,our_unit_size,our_unit_alive_force,our_cas,enemy_unit,enemy_unit_size,enemy_unit_alive_force,enemy_cas,result
0,2026-01-09 06:00:00,b1,CM,100,0,a2,PT,25,25,победа

In [2]:
current_time = next_turn(current_time)

In [5]:
calculate_force(attackers)

(200, 0)

2026-01-09 06:45:00

        ######
        b1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?


        ######
        a2
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 0 ?

enemy_unit_id id1 ?

berserk_mode 0 ?

a2  вжат землю
атака без ответа
разгром
0.65 0.03
25

AttributeError: 'Unit' object has no attribute 'name'

In [31]:
pd.DataFrame([['1',1,1]],columns=['a','b','v'])

   a  b  v
0  1  1  1

In [28]:
logs

Empty DataFrame
Columns: []
Index: []

In [12]:
# прибавить 15 минут
current_dt

In [13]:
str(current_dt)

'2026-01-09 06:15:00'

In [ ]:



print("Через 15 минут:", current_dt)

(200, 0)

        ######
        b1
        ######

elev_pos 0 ?

cover_level 0 ?

target_distance 2 ?

 1

enemy_unit_id a2 ?

berserk_mode 1 ?

        ######
        a2
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 2 ?

 1

enemy_unit_id b1 ?

berserk_mode 0 ?

a2  вжат землю
победа
0.18 0.03
7 2

In [41]:
calculate_force(attackers)

(200, 0)