In [5]:
import pandas as pd
from datetime import datetime
import wm_tac_ops as ops
from ground_engine import GroundEngine, BattleContext

logs = pd.DataFrame(columns=[
    'current_time','initiator',
    'log_blue_id','log_blue_type','log_blue_inf_force','log_blue_arm_force',
    'log_blue_cas_inf','log_blue_cas_armor',
    'log_red_id','log_red_type','log_red_inf_force','log_red_arm_force',
    'log_red_cas_inf','log_red_cas_armor',
    'log_attack_type','log_result'
])

blue = ops.create_inf('blue_com', 100, 'blue')
red = ops.create_mech('red_inf', 50, 'red_arm',5, 'red')[0]

engine = GroundEngine()
context = BattleContext(
    attacker_cover=1,
    defender_cover=2,
    attacker_elevation=0,
    defender_elevation=0,
    distance=2,
    defender_returns_fire=True,
    attacker_berserk=False,
    defender_berserk=False,
)

result = engine.resolve_engagement(
    attacker=blue,
    defender=red,
    context=context,
    logs=logs,
    current_time=datetime(2026, 4, 19, 12, 15)
)
logs = result.logs

In [7]:
result = engine.resolve_engagement(
    attacker=blue,
    defender=red,
    context=context,
    logs=logs,
    current_time=datetime(2026, 4, 19, 12, 15)
)
logs = result.logs

In [8]:
logs

,current_time,initiator,log_blue_id,log_blue_type,log_blue_inf_force,log_blue_arm_force,log_blue_cas_inf,log_blue_cas_armor,log_red_id,log_red_type,log_red_inf_force,log_red_arm_force,log_red_cas_inf,log_red_cas_armor,log_attack_type,log_result
0,2026-04-19 12:00:00,blue,blue_com,inf,100,0,12,0,red_inf,mech,50,5,2,0,inf_attacks_mech,засада
1,2026-04-19 12:15:00,blue,blue_com,inf,88,0,0,0,red_inf,mech,48,5,14,3,inf_attacks_mech,разгром

In [38]:
result.logs

,current_time,initiator,log_blue_id,log_blue_type,log_blue_inf_force,log_blue_arm_force,log_blue_cas_inf,log_blue_cas_armor,log_red_id,log_red_type,log_red_inf_force,log_red_arm_force,log_red_cas_inf,log_red_cas_armor,log_attack_type,log_result
0,2026-04-19 12:00:00,blue,blue_plt,inf,21,0,2,0,red_plt,inf,25,0,0,0,inf_attacks_inf,победа
1,2026-04-19 12:00:00,blue,blue_plt,inf,21,0,0,0,red_plt,inf,22,0,3,0,inf_attacks_inf,разгром
2,2026-04-19 12:00:00,blue,blue_plt,inf,12,0,9,0,red_plt,inf,22,0,0,0,inf_attacks_inf,засада

In [36]:
logs

,current_time,initiator,log_blue_id,log_blue_type,log_blue_inf_force,log_blue_arm_force,log_blue_cas_inf,log_blue_cas_armor,log_red_id,log_red_type,log_red_inf_force,log_red_arm_force,log_red_cas_inf,log_red_cas_armor,log_attack_type,log_result
0,2026-04-19 12:00:00,blue,blue_plt,inf,21,0,2,0,red_plt,inf,25,0,0,0,inf_attacks_inf,победа
1,2026-04-19 12:00:00,blue,blue_plt,inf,21,0,0,0,red_plt,inf,22,0,3,0,inf_attacks_inf,разгром