In [ ]:
armor = pd.DataFrame([[1,'apc',9,8,0],
                  [2,'apc',9,8,0]],columns=['armor_id','type','transport','power','kill_count'])

In [1]:
from datetime import datetime, timedelta
import itertools
from collections import Counter
import matplotlib.pyplot as plt
import random 
from typing import Optional
##### import random
from collections import Counter
import wm_unit as wmu
import pandas as pd

def calculate_force(force):
    available_force = 0
    casualties = 0
    for i in force:
        available_force += len(i.alive_df)
        casualties += len(i.cas_df)
    return available_force,casualties

def next_turn(current_time):
    current_time += timedelta(minutes=15)
    print(current_time)
    return current_time


def evacuation_and_regroup(unit,cas_avacuated,current_time):
    cas_to_add = unit.cas_df
    cas_to_add['side'] = unit.side
    cas_to_add['unit'] = unit.unit_id
    cas_to_add['evac_time'] = current_time
    cas_avacuated = cas_avacuated.append(cas_to_add)
    if 0 < len(unit.alive_df) <= 12:
        unit.size = 'SQ'
    elif 13 < len(unit.alive_df) <= 40:
        unit.size = 'PT'
    elif len(unit.alive_df) > 40:
        unit.size = 'CM'
    if 'type' in unit.alive_df.columns:
        unit.size = 'ARMOR'
    unit.cas_df = pd.DataFrame()
    
    return unit, cas_avacuated


def abandon_cas(unit,cas_abandoned,current_time):
    cas_to_add = unit.cas_df
    cas_to_add['side'] = unit.side
    cas_to_add['unit'] = unit.unit_id
    cas_to_add['evac_time'] = current_time
    cas_abandoned = cas_abandoned.append(cas_to_add)
    unit.cas_df = pd.DataFrame()    

    return unit, cas_abandoned

def save_units(list_of_sides):
    for side in list_of_sides:
        for podr in side:
            podr.alive_df.to_csv(podr.unit_id+'.csv',index=False)

            
def load_units(list_of_sides):
    for side in list_of_sides:
        for podr in side:
            podr.alive_df = pd.read_csv(podr.unit_id+'.csv')


wf = pd.read_excel('A1.xlsx').iloc[:100]
c1 = wmu.Unit(unit_id="c1",  alive_df=wf,  cas_df=pd.DataFrame(),side='blue')
c2 = wmu.Unit(unit_id="c2",  alive_df=wf,  cas_df=pd.DataFrame(),side='blue')
c3 = wmu.Unit(unit_id="c3",  alive_df=wf,  cas_df=pd.DataFrame(),side='blue')

ws = pd.read_excel('A1.xlsx').iloc[:40]

p1 = wmu.Unit(unit_id="p1",  alive_df=ws,  cas_df=pd.DataFrame(),side='red')
p2 = wmu.Unit(unit_id="p2",  alive_df=ws,  cas_df=pd.DataFrame(),side='red')
p3 = wmu.Unit(unit_id="p3",  alive_df=ws,  cas_df=pd.DataFrame(),side='red')


defenders = [p1,p2,p3]
attackers = [c1,c2,c3]

current_time = datetime(2026,1,21,13,0)
logs = pd.DataFrame()
cas_avacuated = pd.DataFrame()
cas_abandoned = pd.DataFrame()

In [24]:
ws = pd.read_excel('A1.xlsx').iloc[:60]

In [25]:
ec1 = wmu.Unit(unit_id="ec1",  alive_df=ws,  cas_df=pd.DataFrame(),side='red')
ec2 = wmu.Unit(unit_id="ec2",  alive_df=ws,  cas_df=pd.DataFrame(),side='red')

defenders = [p1,p2,p3,ec1,ec2]
attackers = [c1,c2,c3]

In [68]:
save_units([defenders,attackers])

In [70]:
load_units([attackers])

In [40]:
str(current_time)

'2026-01-21 14:15:00'

In [37]:
calculate_force(defenders)

(201, 39)

In [38]:
calculate_force(attackers)

(239, 61)

In [39]:
logs

,time,attack_unit_side,attack_unit,attack_unit_size,attack_unit_alive_force,attack_cas,defend_unit,defend_unit_size,defend_unit_alive_force,defend_cas,result
0,2026-01-21 13:00:00,blue,c1,CM,100,0,p2,PT,40,11,победа
0,2026-01-21 13:00:00,blue,c2,CM,100,10,p1,PT,40,2,поражение
0,2026-01-21 13:30:00,blue,c1,CM,100,4,p3,PT,40,20,разгром
0,2026-01-21 13:30:00,blue,c2,CM,90,45,p1,PT,38,0,засада
0,2026-01-21 14:00:00,blue,c3,CM,100,2,ec1,CM,60,1,ничья
0,2026-01-21 14:00:00,blue,c1,CM,96,0,p1,PT,38,1,ничья
0,2026-01-21 14:15:00,blue,c3,CM,98,0,ec1,CM,59,0,ничья
0,2026-01-21 14:15:00,blue,c1,CM,96,0,p1,PT,37,4,победа

In [41]:
current_time = next_turn(current_time)

2026-01-21 14:30:00

In [42]:
logs = c3.attack_unit(ec1,logs,current_time)

        ######
        c3
        ######

elev_pos 0 ?

cover_level 1 ?

target_distance 4 ?

enemy_unit_id ec1 ?

berserk_mode 1 ?


        ######
        ec1
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 3 ?

enemy_unit_id c3 ?

berserk_mode 0 ?

победа
0.18 0.03
3 1

In [43]:
ec1

Unit(unit_id=ec1, size=CM, alive_df=56, cas_df=4, last_parameters={'elev_pos': 0, 'cover_level': 2, 'target_distance': 3, 'enemy_unit_id': 'c3', 'berserk_mode': 0})

In [33]:
logs = c1.attack_unit(p1,logs,current_time)

        ######
        c1
        ######

elev_pos 0 ?

cover_level 1 ?

target_distance 4 ?

enemy_unit_id p1 ?

berserk_mode 1 ?


        ######
        p1
        ######

elev_pos 0 ?

cover_level 2 ?

target_distance 4 ?

enemy_unit_id c1 ?

berserk_mode 0 ?

победа
0.18 0.03
4 0

In [44]:
logs[logs['defend_unit']=='ec1']

,time,attack_unit_side,attack_unit,attack_unit_size,attack_unit_alive_force,attack_cas,defend_unit,defend_unit_size,defend_unit_alive_force,defend_cas,result
0,2026-01-21 14:00:00,blue,c3,CM,100,2,ec1,CM,60,1,ничья
0,2026-01-21 14:15:00,blue,c3,CM,98,0,ec1,CM,59,0,ничья
0,2026-01-21 14:30:00,blue,c3,CM,98,1,ec1,CM,59,3,победа

In [34]:
p1

Unit(unit_id=p1, size=PT, alive_df=33, cas_df=7, last_parameters={'elev_pos': 0, 'cover_level': 2, 'target_distance': 4, 'enemy_unit_id': 'c1', 'berserk_mode': 0})

In [86]:
b1, cas_avacuated = evacuation_and_regroup(b1,cas_avacuated,current_time)

<ipython-input-68-00212c09020b>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cas_avacuated = cas_avacuated.append(cas_to_add)

In [16]:
w5, cas_abandoned = abandon_cas(w5,cas_abandoned,current_time)

<ipython-input-2-d3cb3ba4e177>:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cas_abandoned = cas_abandoned.append(cas_to_add)

In [76]:
for side in [defenders, attackers]:
    for podr in side:
        podr.alive_df.to_csv(podr.unit_id+'.csv',index=False)